export const transactionsData = [
  {
    name: "Electricity Bill",
    category: "Rent & Living",
    date: "2026-03-01",
    time: "04:28:48",
    amount: 29581,
    note: "Payment for monthly electricity bill",
    status: "Failed",
  },
  {
    name: "Weekly Groceries",
    category: "Food & Drinks",
    date: "2026-03-04",
    time: "04:28:48",
    amount: 20407,
    note: "Groceries shopping at local supermarket",
    status: "Completed",
  },
  {
    name: "Movie Night",
    category: "Entertainment",
    date: "2026-02-27",
    time: "04:28:48",
    amount: 9784,
    note: "Tickets for movies and snacks",
    status: "Pending",
  },
  {
    name: "Movie Night",
    category: "Entertainment",
    date: "2026-02-27",
    time: "04:28:48",
    amount: 9784,
    note: "Tickets for movies and snacks",
    status: "Pending",
  },
  {
    name: "Movie Night",
    category: "Entertainment",
    date: "2026-02-27",
    time: "04:28:48",
    amount: 9784,
    note: "Tickets for movies and snacks",
    status: "Pending",
  },
]
